config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
    get 'home/about' => 'homes#about', as: 'about'

  get "search" => "searches#search"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #リレーション
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #フォロー、フォロワーの関係
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  #フォロー一覧画面
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower

  #フォローするときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end

  #フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_users.include?(user)
  end

  #バリデーション
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  #プロフィール画像
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_math"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  #フォロー一覧

  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end

  #フォロワー一覧
  def followers
    user = User.find(params[:id])
    @user = user.follower_users
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3>User info</h3>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= image_tag user.get_profile_image(100, 100) %>
    </div>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <th>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <th>Follows</th>
        <td>
          <%= link_to followers_user_path(user) do %>
            <h6><%= user.followers.count %></h6>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Followers</th>
        <td>
          <%= link_to followers_user_path(user) do %>
            <h6><%= user.followeds.count %></h6>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-sm btn-block' do %>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h2>User info</h2>
      <%= render "layouts/error_message", obj: @user %>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :Image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :Introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit  "Update user", class: 'btn btn-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follows</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image(50, 50) %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <h6>フォロー<%= user.followers.count %></h6>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <h6>フォロワー<%= user.followeds.count %></h6>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/follows.html.erb
<h2>Follows</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image(50, 50) %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <h6>フォロー<%= user.followers.count %></h6>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <h6>フォロワー<%= user.followeds.count %></h6>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="row">
        <%= render "users/info", user: current_user %>
      </div>
      <div class="row">
        <%= render "books/new", book: @book %>
      </div>
    </div>
    <div class="col-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100, 100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "show", user_path(user.id) %></td>
              <td>フォロー<%= user.followers.count %></td>
              <td>フォロワー<%= user.followeds.count %></td>
              <td>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-danger" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="row">
        <%= render "users/info", user: @user %>
      </div>
      <div class="row">
        <%= render "books/new", book: @book %>
      </div>
    </div>
    <div class="col-6">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>